
# Site settings
title: Xixu Hu
email: xixuhu1998@gmail.com
description: My homepage

  
url: "https://xixuhu.github.io/" # the base hostname & protocol for your site

# User setting
owner:
email: xixuhu1998@gmail.com
facebook_username:
twitter_username:
github_username: XixuHu
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      mathjax: "true"
      commentable: "true"
      toc: "true"
      layout : "post"

